### PR TITLE
Tasks modules created w/ basic functionality

### LINKED ISSUE #19: Task Data Provider
- create data provider for tasks
     - getTasks, getTaskById, addTask, deleteTask, updateTask, completeTask
       
     - create & export TaskContext in order to 
        pass data to components

### LINKED ISSUE #35: Task Form Component
- add Task button shows on DOM
- input fields for name, expectedCompletion.
- createTask button renders newTask to DOM

### LINKED ISSUE #36: Task List Component
- renders tasks to DOM w/ buttons for 'completed' and 'delete'
(button functionality not complete at this time)
- renders button for 'add Task'

### LINKED ISSUE #37: Task Card Component
- TaskCard renders individual tasks to TaskList
- TaskCard has basic CSS

### PR DESCRIPTION
**Pull request by nathanRomad**
feat: created TaskProvider TaskList TaskCard TaskForm Tasks.css / data provider functional / TaskList is rendering buttons and tasks to DOM / TaskCard renders individual tasks / TaskForm renders when add Task is clicked

# Description
- created dataProvider and included methods for getTasks, getTasksById, addTask, deleteTask
- created basic form for name and expectedCompletion date. //need to add <label&input> for taskDetails.
- individual tasks are rendering to DOM and have buttons for 'completed' and 'delete' //need to finish button functionality

## Type of change

Please delete options that are not relevant.

- [X] New feature (non-breaking change which adds functionality)
- [X] NON-Breaking change
- [X] This change requires a documentation update

# Testing Instructions
git fetch --all
git checkout nah-createTasks
make sure your server is running (npm start)
use login to gain access to application
click on tasks on header
click on add Task and fill out the form / click on create Task
page renders back to Tasks with new task on DOM

// delete and complete are NOT functional at this time

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] My changes generate no new warnings or errors
        - src/components/auth/Login.js error is still present 
- [X] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by nathanRomad** [comment]
- updated taskForm to include a <textarea> for taskDetails
- added taskDetails to Tasks table in ERD
- added taskDetails to database.json (discussed with Team prior)

**Comment by nathanRomad** [comment]
delete button is functional

**Comment by nathanRomad** [comment]
BLU and ERICA helped me find the error! I was passing "0" as the initial userId in my state variable.
Handle delete function was messing up my fetch call..
but changing my TaskForm to check for the userId based on the user who is logged in..

https://github.com/nss-day-cohort-46/reactive-nutshell-gauntlets-of-adventure-1/blob/711fa03959af6775ac362064daa8990247bc854

**Comment by nathanRomad** [comment]
need to work on: preventing the task from being displayed in the list after 'Completed Task' is clicked.

**Review by daprieu — APPROVED** [review]
I am able to view tasks!
add new Tasks!
change Tasks to complete!
and Delete Tasks!

**Review by blusanders — APPROVED** [review]
Tasks render
Add task works
Delete task works

**Pull request merged**
