### PR TITLE
Bs message add friend

### PR DESCRIPTION
**Pull request by blusanders**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Messages rendering properly
Deleting properly
Adding properly

Working on add friend from chat next

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Testing Instructions

Please describe the tests required to verify your changes. Provide instructions so PR Tester can check functionality. Please also list any relevant details for your tests

git fetch --all
git checkout bs-messageAddFriend

# Checklist:

- [ ] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings or errors
- [ ] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by Younique98 — APPROVED** [review]
It all works. Does the add button suppose to do anything yet?

**Review by daprieu — APPROVED** [review]
I am able to add messages and date shows with message of date posted.
Deleting messages also is working.

**Review by nathanRomad — APPROVED** [review]
can create new messages!
can see the new message render to DOM when created.
can delete messages from the current logged in user.
I can see the 'add' button to eventually add a friend whose message I am viewing.

**Comment by nathanRomad** [comment]
This really looks great Blu!  I love the minimalistic view and the clean buttons!

**Pull request merged**
