### PR TITLE
Et fixed broken timestamp

### PR DESCRIPTION
**Pull request by Younique98**
# Description

Fixed the timestamp and added Date.now() to the NewsForm.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Testing Instructions
`
git checkout main
git fetch --all
git checkout et-fixed-broken-timestamp
`
Please describe the tests required to verify your changes. Provide instructions so PR Tester can check functionality. Please also list any relevant details for your tests

# Checklist:

- [ x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings or errors
- [ ] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by nathanRomad — APPROVED** [review]
Looks like the timestamp is working correctly now for Articles!

**Review by nathanRomad — APPROVED** [review]
be sure to check ApplicationViews for any conflicts.
accepting incoming changes looks like it will solve the issue.

The article feature looks good and I can see the correct timestamp on my Articles.

**Comment by nathanRomad** [comment]
tested branch!  everything looks good!
Be sure to double check ApplicationViews for conflicts, otherwise, this looks great!

**Comment by Younique98** [comment]
new pull request opened on a different branch with all the new functionality needed.

**Pull request closed without merging**
